FROM ubuntu:focal

RUN apt update && apt install -y software-properties-common
RUN add-apt-repository -y ppa:deadsnakes/ppa && apt update
RUN apt install -y \
    net-tools \
    iputils-ping \
    iproute2 \
    curl \
    python3.10
RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10
RUN pip install pymodbus

CMD ["/bin/bash"]